# DAT210x - Programming with Python for DS

## Module2 - Lab2

In [1]:
# Import and alias Pandas
import pandas as pd

Write code below to load up the `tutorial.csv` dataset. You can store it into a variable called df:

In [2]:
import pandas as pd
df = pd.read_csv("Datasets/tutorial.csv")
df

       col0      col1      col2      col3
0 -0.722876 -1.330682  1.309208  0.232378
1  1.160396 -0.730879  0.677368  1.044722
2 -1.062870 -0.503704 -0.238536 -1.417937
3  0.437078  0.362640 -0.111228 -1.649853

Now that your dataset has been loaded, invoke the `.describe()` method to display some results about it:

In [3]:
df.describe()

           col0      col1      col2      col3
count  4.000000  4.000000  4.000000  4.000000
mean  -0.047068 -0.550656  0.409203 -0.447672
std    1.029715  0.701720  0.723956  1.300815
min   -1.062870 -1.330682 -0.238536 -1.649853
25%   -0.807875 -0.880830 -0.143055 -1.475916
50%   -0.142899 -0.617291  0.283070 -0.592780
75%    0.617907 -0.287118  0.835328  0.435464
max    1.160396  0.362640  1.309208  1.044722

Another _very_ useful method you can use to get an overview of your data is by using the `.summary()` method. This returns even more details than `.describe()`. Try it out below:

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
col0    4 non-null float64
col1    4 non-null float64
col2    4 non-null float64
col3    4 non-null float64
dtypes: float64(4)
memory usage: 200.0 bytes

Lastly, try experimenting with indexing. Figure out which _indexing method_ you would need to use in order to index your dataframe with: `[2:4, 'col3']`. Finally, display the results:

In [4]:
df.loc[2:4,'col3']

2   -1.417937
3   -1.649853
Name: col3, dtype: float64

In [16]:
rk = range(1,41)
rk_df = pd.DataFrame(rk)
rk_df.columns = ['rk']
rk_df

    rk
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
9   10
10  11
11  12
12  13
13  14
14  15
15  16
16  17
17  18
18  19
19  20
20  21
21  22
22  23
23  24
24  25
25  26
26  27
27  28
28  29
29  30
30  31
31  32
32  33
33  34
34  35
35  36
36  37
37  38
38  39
39  40

In [27]:
import pandas as pd

# read nfl players csv
nfl_data = pd.read_csv('Datasets/nfl_players.csv')
nfl_data

ValueError: labels ['RK'] not contained in axis

In [48]:
nfl_raw

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,NaN,PP,SH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,RK,PLAYER,TEAM,GP,G,A,PTS,+/-,PIM,PTS/G,SOG,PCT,GWG,G,A,G,A
2,1,"Jamie Benn, LW",DAL,82,35,52,87,1,64,1.06,253,13.8,6,10,13,2,3
3,2,"John Tavares, C",NYI,82,38,48,86,5,46,1.05,278,13.7,8,13,18,0,1
4,3,"Sidney Crosby, C",PIT,77,28,56,84,5,47,1.09,237,11.8,3,10,21,0,0
5,4,"Alex Ovechkin, LW",WSH,81,53,28,81,10,58,1.00,395,13.4,11,25,9,0,0
6,NaN,"Jakub Voracek, RW",PHI,82,22,59,81,1,78,0.99,221,10.0,3,11,22,0,0
7,6,"Nicklas Backstrom, C",WSH,82,18,60,78,5,40,0.95,153,11.8,3,3,30,0,0
8,7,"Tyler Seguin, C",DAL,71,37,40,77,-1,20,1.08,280,13.2,5,13,16,0,0
9,8,"Jiri Hudler, LW",CGY,78,31,45,76,17,14,0.97,158,19.6,5,6,10,0,0
10,NaN,"Daniel Sedin, LW",VAN,82,20,56,76,5,18,0.93,226,8.9,5,4,21,0,0
11,10,"Vladimir Tarasenko, RW",STL,77,37,36,73,27,31,0.95,264,14.0,6,8,10,0,0
12,NaN,PP,SH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,RK,PLAYER,TEAM,GP,G,A,PTS,+/-,PIM,PTS/G,SOG,PCT,GWG,G,A,G,A
14,NaN,"Nick Foligno, LW",CBJ,79,31,42,73,16,50,0.92,182,17.0,3,11,15,0,0
15,NaN,"Claude Giroux, C",PHI,81,25,48,73,-3,36,0.90,279,9.0,4,14,23,0,0
16,NaN,"Henrik Sedin, C",VAN,82,18,55,73,11,22,0.89,101,17.8,0,5,20,0,0
17,14,"Steven Stamkos, C",TB,82,43,29,72,2,49,0.88,268,16.0,6,13,12,0,0
18,NaN,"Tyler Johnson, C",TB,77,29,43,72,33,24,0.94,203,14.3,6,8,9,0,0
19,16,"Ryan Johansen, C",CBJ,82,26,45,71,-6,40,0.87,202,12.9,0,7,19,2,0
20,17,"Joe Pavelski, C",SJ,82,37,33,70,12,29,0.85,261,14.2,5,19,12,0,0
21,NaN,"Evgeni Malkin, C",PIT,69,28,42,70,-2,60,1.01,212,13.2,4,9,17,0,0
22,NaN,"Ryan Getzlaf, C",ANA,77,25,45,70,15,62,0.91,191,13.1,6,3,10,0,2
23,20,"Rick Nash, LW",NYR,79,42,27,69,29,36,0.87,304,13.8,8,6,6,4,1
24,NaN,PP,SH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,RK,PLAYER,TEAM,GP,G,A,PTS,+/-,PIM,PTS/G,SOG,PCT,GWG,G,A,G,A
26,21,"Max Pacioretty, LW",MTL,80,37,30,67,38,32,0.84,302,12.3,10,7,4,3,2
27,NaN,"Logan Couture, C",SJ,82,27,40,67,-6,12,0.82,263,10.3,4,6,18,2,0
28,23,"Jonathan Toews, C",CHI,81,28,38,66,30,36,0.81,192,14.6,7,6,11,2,1
29,NaN,"Erik Karlsson, D",OTT,82,21,45,66,7,42,0.80,292,7.2,3,6,24,0,0
30,NaN,"Henrik Zetterberg, LW",DET,77,17,49,66,-6,32,0.86,227,7.5,3,4,24,0,0
31,26,"Pavel Datsyuk, C",DET,63,26,39,65,12,8,1.03,165,15.8,5,8,16,0,0
32,NaN,"Joe Thornton, C",SJ,78,16,49,65,-4,30,0.83,131,12.2,0,4,18,0,0
33,28,"Nikita Kucherov, RW",TB,82,28,36,64,38,37,0.78,190,14.7,2,2,13,0,0
34,NaN,"Patrick Kane, RW",CHI,61,27,37,64,10,10,1.05,186,14.5,5,6,16,0,0
35,NaN,"Mark Stone, RW",OTT,80,26,38,64,21,14,0.80,157,16.6,6,5,8,1,0
36,NaN,PP,SH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,RK,PLAYER,TEAM,GP,G,A,PTS,+/-,PIM,PTS/G,SOG,PCT,GWG,G,A,G,A
38,NaN,"Alexander Steen, LW",STL,74,24,40,64,8,33,0.86,223,10.8,5,8,16,0,0
39,NaN,"Kyle Turris, C",OTT,82,24,40,64,5,36,0.78,215,11.2,6,4,12,1,0
40,NaN,"Johnny Gaudreau, LW",CGY,80,24,40,64,11,14,0.80,167,14.4,4,8,13,0,0
41,NaN,"Anze Kopitar, C",LA,79,16,48,64,-2,10,0.81,134,11.9,4,6,18,0,0
42,35,"Radim Vrbata, RW",VAN,79,31,32,63,6,20,0.80,267,11.6,7,12,11,0,0
43,NaN,"Jaden Schwartz, LW",STL,75,28,35,63,13,16,0.84,184,15.2,4,8,8,0,2
44,NaN,"Filip Forsberg, C",NSH,82,26,37,63,15,24,0.77,237,11.0,6,6,13,0,0
45,NaN,"Jordan Eberle, RW",EDM,81,24,39,63,-16,24,0.78,183,13.1,2,6,15,0,0
46,NaN,"Ondrej Palat, LW",TB,75,16,47,63,31,24,0.84,139,11.5,5,3,8,1,1
47,40,"Zach Parise, LW",MIN,74,33,29,62,21,41,0.84,259,12.7,3,11,5,0,0